"""empty message

Revision ID: 725fa9b0c66e
Revises: 8f932fae97c8
Create Date: 2023-02-23 19:34:30.935097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725fa9b0c66e'
down_revision = '8f932fae97c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
